// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXOprI9BpVYAtkq_xSyWGnMoOO7p1jqz0',
    appId: '1:908432605117:web:27abb9bead5bcd0a101cd4',
    messagingSenderId: '908432605117',
    projectId: 'travel-app-684dc',
    authDomain: 'travel-app-684dc.firebaseapp.com',
    storageBucket: 'travel-app-684dc.firebasestorage.app',
    measurementId: 'G-PW076W6DGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdE6SEyrcQk11pvtoh9pJcC7_YRH_xIw',
    appId: '1:908432605117:android:8476e0f5cf4829e4101cd4',
    messagingSenderId: '908432605117',
    projectId: 'travel-app-684dc',
    storageBucket: 'travel-app-684dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCTHq8Tu8BPlunO2zc4Z_QJgY5p6nZpso',
    appId: '1:908432605117:ios:752ab9d51347e0e8101cd4',
    messagingSenderId: '908432605117',
    projectId: 'travel-app-684dc',
    storageBucket: 'travel-app-684dc.firebasestorage.app',
    iosBundleId: 'com.example.createTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCTHq8Tu8BPlunO2zc4Z_QJgY5p6nZpso',
    appId: '1:908432605117:ios:752ab9d51347e0e8101cd4',
    messagingSenderId: '908432605117',
    projectId: 'travel-app-684dc',
    storageBucket: 'travel-app-684dc.firebasestorage.app',
    iosBundleId: 'com.example.createTrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXOprI9BpVYAtkq_xSyWGnMoOO7p1jqz0',
    appId: '1:908432605117:web:2ea3241294a7dab8101cd4',
    messagingSenderId: '908432605117',
    projectId: 'travel-app-684dc',
    authDomain: 'travel-app-684dc.firebaseapp.com',
    storageBucket: 'travel-app-684dc.firebasestorage.app',
    measurementId: 'G-87PQLTEQMB',
  );

}